### PR TITLE
Hydra v0: cleaning up run.py

### PR DESCRIPTION
**Pull request by vict0rsch**
* delete `tune` -> now a flag `--tune` for @pg2455 
* rename `sim` to `main` and `run_simu` to `simulate`

### CODE REVIEW

**Comment by pg2455** [comment]
@mweiss17  - Are the tests failing because of runtime warnings? If that's true, a lot of tests will fail.

**Comment by mweiss17** [comment]
This looks good -- I'm not sure what happened with the tests. I have a PR forthcoming to update the tests to use pytest and codecov. We should merge it and then run the tests locally on this PR to figure out what's going on.

**Comment by mweiss17** [comment]
no, tests were failing for other reasons. I merged my tests fixes (also in PR, but about to be merged by PLSC) and got the tests running locally. They should be about to pass here

**Review by mweiss17 — APPROVED** [review]
Looks good now, tests pass

**Comment by vict0rsch** [comment]
yeeey

**Pull request merged**
