### PR TITLE
[WIP do not merge] Symptom fixes/changes and initial viral load

### PR DESCRIPTION
**Pull request by teganmaharaj**
Symptoms changed to have more realistic and smooth progressions. 
Initial viral load computed additively in the "at" method.
Symptoms and viral load progression made to depend on initial viral load. As a result, had to remove computation of these to the moment someone is infected.

Currently there is a bug, not sure where - somehow viral load curve is not initialized for someone with an infection timestamp (should be happening in the at method), causing an error because the viral load curve is None when computing the @property viral_load. This shouldn't be able to happen.

### CODE REVIEW

**Comment by teganmaharaj** [comment]
I'd also like help writing some tests/metrics which compute number of people with different symptoms (could be a separate PR)

**Comment by teganmaharaj** [comment]
Should I close this PR since it should be to the dev branch now?

**Comment by mweiss17** [comment]
I think so -- it sounds like we should move over to develop while getting the intervention study out. This will reduce the number of PR

**Comment by mweiss17** [comment]
I'm going to close this in favor of focusing on updating the develop branch for running intervention studies. We can re-open it in the future if need be.

**Pull request closed without merging**
