### PR TITLE
Merge master changeset from Martin (2020/04/24)

### PR DESCRIPTION
**Pull request by plstcharles**
I have not ran any tests on this yet, just putting up the PR; it's a hearthy diff.

Will probably try to merge this later today (after testing...) to ensure that both repos don't diverge too far from now on.

An equivalent merge will be made on Martin's side in a few moments --- unfortunately, rebasing Martin's code on this master was pretty much impossible, so the history will not be perfectly aligned.

### CODE REVIEW

**Comment by plstcharles** [comment]
Current tests fail because of a hard-coded check to a "Human" attribute, i.e. the number of observed symptoms:
https://github.com/pg2455/covid_p2p_simulation/blob/master-merged-20200424/tests/models_test.py#L102
I fixed a few issues in the tests already, but I'm not too sure how to handle this one...

@satyaog is this a test you recognize?

We should fix the test (...or disable it, since it was already broken in Martin's fork) to get this PR merged ASAP.

**Comment by plstcharles** [comment]
Fixing the tests is taken a lot longer than anticipated, will probably be working on this tomorrow as well

**Comment by plstcharles** [comment]
All tests now seem OK (finally!) --- let me know if you see anything else that needs cleaning

**Comment by plstcharles** [comment]
@teganmaharaj  :  @pg2455 and I just had a chat on the changes to simulator.py and utils.py in this PR, and were wondering if you could confirm that the +/- proposed here are OK and won't revert any useful stuff in @pg2455 's master --- could you take a look?

**Comment by teganmaharaj** [comment]
I like the new format!
I'm assuming the numbers (e.g. age) are like bin edges; are they inclusive?  In the previous code it was clear that they were *not* inclusive (e.g. if rand() < 60 does not include 60). I don't think it's a big deal either way, but the numbers I put in were from data based on non-inclusive bin edges.

I also don't understand how we make conditions here conditional on other conditions ( :) ) e.g. changing the probability of heart disease if you're a smoker.

**Comment by plstcharles** [comment]
Good questions --- I didn't keep track of who made the changes, maybe @mweiss17 can tell us more?

**Comment by mweiss17** [comment]
@satyaog made the changes to the symptoms data structure. I sadly think we should close this PR and just merge the interventions branch. On that one, I have removed DummyHuman and now we're just passing around Humans, so it's a pretty major shift. It also removes the re-instantiation of humans from logs, which is error-prone. I can try to get the tests passing on there.

**Comment by plstcharles** [comment]
No worries, I agree the interventions branch would indeed be a cleaner sync point --- I'll close this one and reopen another one later today, I should be able to cherry-pick the test fixes pretty easily

**Pull request closed without merging**
