### PR TITLE
Disabling Proximity factor

### PR DESCRIPTION
**Pull request by pg2455**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #[ISSUE_NUMBER]

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

1. Changed `INFECTION_DISTANCE_FACTOR` and `INFECTION_DURATION_FACTOR` to 0 to disable proximity factor
2. Added `get_R0` in `track.py` to fix the indexing error in case of smaller `simulation_days`
3. Changed `simulation_days` in `run.py` to 30 for default.

- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by plstcharles — APPROVED** [review]
Looks good to me, I can't validate the changes to the R0 logic but everything seems clean+modular.

Feel free to merge if nobody else has comments

**Comment by obilaniu** [comment]
So what does disabling the proximity factor really do?

**Comment by pg2455** [comment]
As of now, `p_infection` doesn't depend on distance and duration in a linear fashion. It is only used as a boolean factor. If the conditions are satisfied, we use `p_infection`.  `p_infection` should depend on the value of distance and duration too. We haven't thought it through, so these are just the placeholders for now.

**Review by obilaniu — APPROVED** [review]
@pg2455 Ok. Let's get it merged.

**Pull request merged**
